src/QNA/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.qna_main, name='qna_main'),
    url(r'^list/$', views.question_list, name='question_list'),
    url(r'^(?P<pk>\d+)/$', views.question_detail, name='question_detail'),
    url(r'^new/$', views.question_new, name='question_new'),
    url(r'^(?P<pk>\d+)/edit/$', views.question_edit, name='question_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.question_delete, name='question_delete'),
    url(r'^(?P<pk>\d+)/answer/new/$', views.answer_new, name='answer_new'),
    url(r'^(?P<pk>\d+)/answer/(?P<answer_pk>\d+)/edit/$', views.answer_edit, name='answer_edit'),
    url(r'^(?P<pk>\d+)/answer/(?P<answer_pk>\d+)/delete/$', views.answer_delete, name='answer_delete'),
    url(r'^FAQ/$', views.faq_list, name='faq_list'),
    url(r'^FAQ/(?P<pk>\d+)/$', views.faq_detail, name='faq_detail'),



]

src/accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login
from django.conf.urls.static import static
from django.conf import settings

from . import views
from .forms import LoginForm

urlpatterns = [
    url(r'^signupchoice/$', views.signup_choice, name='signup_choice'),
    url(r'^mentor_signup/$', views.mentor_signup, name='mentor_signup'),
    url(r'^mentee_signup/$', views.mentee_signup, name='mentee_signup'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.profile_edit, name='profile_edit'),
    url(r'^login/$', login, kwargs={'authentication_form': LoginForm, }, name='login'),
    url(r'', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/onedayschool/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static


from django.contrib import admin

from mentoring import views as mentoring_views
from accounts import views as accounts_views

urlpatterns = [
    url(r'^$', mentoring_views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^intro/$', mentoring_views.intro, name='intro'),
    url(r'^program_info/$', mentoring_views.program_info, name='program_info'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^mentoring/', include('mentoring.urls')),
    url(r'^Q&A/', include('QNA.urls')),
    url(r'^access_terms/$', accounts_views.access_terms, name='access_terms'),
    url(r'^personal_info_terms/$', accounts_views.personal_info_terms, name='personal_info_terms'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models
from django.conf import settings
from django.core.files import File
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save
from django.contrib.auth.models import User

from onedayschool.utils import thumbnail, random_name_upload_to

MAJOR_CHOICES = (
    ('간호대학', '간호대학'),
    ('건축학과', '건축학과'),
    ('경영대학', '경영대학'),
    ('농경제사회학부', '농경제사회학부'),
    ('사회과학계열', '사회과학계열'),
    ('심리학과', '심리학과'),
    ('소비자아동학부', '소비자아동학부'),
    ('의류학과', '의류학과'),
    ('인문계열', '인문계열'),
    ('언어학과', '언어학과'),
    ('교육학과', '교육학과'),
    ('국어교육과', '국어교육과'),
    ('물리교육과', '물리교육과'),
    ('사회교육과', '사회교육과'),
    ('생물교육과', '생물교육과'),
    ('역사교육과', '역사교육과'),
    ('영어교육과', '영어교육과'),
    ('지구과학교육과', '지구과학교육과'),
    ('지리교육과', '지리교육과'),
    ('체육교육과', '체육교육과'),
    ('화학교육과', '화학교육과'),
    ('수학교육과', '수학교육과'),
    ('물리천문학부', '물리천문학부'),
    ('바이오시스템소재학부', '바이오시스템소재학'),
    ('산림과학부', '산림과학부'),
    ('생명과학부', '생명과학부'),
    ('수리과학부', '수리과학부'),
    ('식물생산과학부', '식물생산과학부'),
    ('식품영양학과', '식품영양학과'),
    ('응용생물화학부', '응용생물화학부'),
    ('화학부', '화학부'),
    ('건설환경공학부', '건설환경공학부'),
    ('기계항공공학부', '기계항공공학부'),
    ('산업공학과', '산업공학과'),
    ('식품동물생명공학부', '식품동물생명공학부'),
    ('재료공학부', '재료공학부'),
    ('전기정보공학부', '전기정보공학부'),
    ('조경지역시스템공학부', '조경지역시스템공학부'),
    ('조선해양공학과', '조선해양공학과'),
    ('컴퓨터공학부', '컴퓨터공학부'),
    ('화학생물공학부', '화학생물공학부'),
    ('의예과', '의예과'),

)

ADMISSION_TYPE_CHOICES = (
    ('지역균형선발전형', '지역균형선발전형'),
    ('일반전형(특기자)', '일반전형(특기자)'),
    ('기회균형선발특별전형', '기회균형선발특별전형'),
    ('정시전형', '정시전형'),

)

GRADE_CHOICES = (
    ('초등학교 1학년', '초등학교 1학년'),
    ('초등학교 2학년', '초등학교 2학년'),
    ('초등학교 3학년', '초등학교 3학년'),
    ('초등학교 4학년', '초등학교 4학년'),
    ('초등학교 5학년', '초등학교 5학년'),
    ('초등학교 6학년', '초등학교 6학년'),
    ('중학교 1학년', '중학교 1학년'),
    ('중학교 2학년', '중학교 2학년'),
    ('중학교 3학년', '중학교 3학년'),
    ('고등학교 1학년', '고등학교 1학년'),
    ('고등학교 2학년', '고등학교 2학년'),
    ('고등학교 3학년', '고등학교 3학년'),
    ('N수생', 'N수생'),
)

ACCESS_ROUTE = (
    ('지인소개', '지인소개'),
    ('학원소개', '학원소개'),
    ('페이스북', '페이스북'),
    ('네이버', '네이버'),
    ('전단지', '전단지'),
    ('기타', '기타'),


)



class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, verbose_name='이름')
    #멘토 only
    major = models.CharField(max_length=40, choices=MAJOR_CHOICES, default='', verbose_name='전공', blank=True)
    phone = models.CharField(max_length=20, null=True, verbose_name='전화번호')
    admission_type = models.CharField(max_length=40, choices=ADMISSION_TYPE_CHOICES, default='', verbose_name='입학 전형')
    is_mentor = models.BooleanField(default=False)
    frequency = models.IntegerField(default=0)
    rating = models.FloatField(blank=True, default=0)
    highschool = models.CharField(blank=True, max_length=40, verbose_name='출신 고등학교')
    image = models.ImageField(blank=True, null=True, upload_to=random_name_upload_to, verbose_name='사진 업로드')
    intro = models.TextField(max_length=300, verbose_name='기타 약력')

    #멘티 only
    grade = models.CharField(max_length=20, verbose_name='학년')
    access_route = models.CharField(max_length=80, choices=ACCESS_ROUTE, verbose_name='가입경로')

    def __str__(self):

        if str(self.is_mentor) == "True":
            return "멘토 ||  "+self.name+" ( ID : "+self.user.username+" , 전화번호 : " + str(self.phone) + " )"
        else:
            return "멘티 ||  "+self.name+" ( ID : "+self.user.username+" )"


def pre_on_mentorimage_save(sender, **kwargs):
    mentor_image = kwargs['instance']
    if mentor_image.image:
        max_width = 800
        if mentor_image.image.width > max_width or mentor_image.image.height > max_width:
            processed_file = thumbnail(mentor_image.image.file, max_width, max_width)
            mentor_image.image.save(mentor_image.image.name, File(processed_file))

pre_save.connect(pre_on_mentorimage_save, sender=Profile)

def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        profile = Profile(user=user)
        profile.save()

post_save.connect(create_profile, sender=User)

src/accounts/forms.py
import re
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import filesizeformat
from django.conf import settings

from .models import Profile, MAJOR_CHOICES, ADMISSION_TYPE_CHOICES, GRADE_CHOICES, ACCESS_ROUTE
from .fields import RestrictedImageField

def phone_validator(value):
    number = ''.join(re.findall(r'\d+', value))
    return RegexValidator(r'^01[016789]\d{7,8}$', message='번호를 입력해주세요')(number)

class MentorForm(UserCreationForm):
    username = forms.CharField(label='아이디')
    password1 = forms.CharField(label='비밀번호', widget=forms.PasswordInput)
    password2 = forms.CharField(label='비밀번호 확인', widget=forms.PasswordInput)
    name = forms.CharField(label='이름')
    major = forms.ChoiceField(label='소속학과', choices=MAJOR_CHOICES)
    admission_type = forms.ChoiceField(label='입학전형', choices=ADMISSION_TYPE_CHOICES)
    highschool = forms.CharField(label='출신고등학교')
    phone = forms.CharField(label='휴대폰 번호', widget=forms.TextInput(attrs={'placeholder': 'ex) 010-1234-5678'}), validators=[phone_validator])
    image = RestrictedImageField(max_upload_size=3145728, label='프로필 사진')
    intro = forms.CharField(label='각종 약력', widget=forms.TextInput(attrs={'placeholder': '멘토링,과외 경험, 각종 대회 수상, 인증시험 등'}))

    #is_agree = forms.BooleanField(label='약관동의', error_messages={
        #'required' : '약관동의를 해주셔야 가입이 됩니다.',
    #})

    error_messages = {
        'password_mismatch': _("비밀번호가 일치하지 않습니다."),
    }

    widgets = {
        'major': forms.RadioSelect(attrs={'style':'display: none'}),
        'admission_type': forms.RadioSelect(attrs={'style':'display: none'}),
        }


    def save(self, commit=True):
        user = super(MentorForm, self).save(commit=False)
        if commit:
            user.save()
            user.profile.name = self.cleaned_data['name']
            user.profile.major = self.cleaned_data['major']
            user.profile.admission_type = self.cleaned_data['admission_type']
            user.profile.highschool = self.cleaned_data['highschool']
            user.profile.phone = self.cleaned_data['phone']
            user.profile.image = self.cleaned_data['image']
            user.profile.intro = self.cleaned_data['intro']
            user.profile.is_mentor = True
            user.profile.save()
        return user


class MentorUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('name', 'major', 'admission_type', 'highschool', 'phone', 'intro', )


class MenteeForm(UserCreationForm):
    username = forms.CharField(label='아이디')
    password1 = forms.CharField(label='비밀번호', widget=forms.PasswordInput)
    password2 = forms.CharField(label='비밀번호 확인', widget=forms.PasswordInput)
    name = forms.CharField(label='이름')
    #major = forms.ChoiceField(label='지망학과', choices=MAJOR_CHOICES)
    #admission_type = forms.ChoiceField(label='희망입시전형', choices=ADMISSION_TYPE_CHOICES)
    #phone = forms.CharField(label='휴대폰 번호', widget=forms.TextInput(attrs={'placeholder': 'ex) 010-1234-5678'}), validators=[phone_validator])
    grade = forms.ChoiceField(label='학년', choices=GRADE_CHOICES)
    access_route = forms.ChoiceField(label='가입경로', choices=ACCESS_ROUTE)
    #is_agree = forms.BooleanField(label='약관동의', error_messages={
    #    'required' : '약관동의를 해주셔야 가입이 됩니다.',
    #})

    error_messages = {
        'password_mismatch': _("비밀번호가 일치하지 않습니다."),
    }

    def save(self, commit=True):
        user = super(MenteeForm, self).save(commit=False)
        if commit:
            user.save()
            user.profile.name = self.cleaned_data['name']
            user.profile.grade = self.cleaned_data['grade']
            user.profile.access_route = self.cleaned_data['access_route']
            user.profile.is_mentor = False
            user.profile.save()
        return user


class MenteeUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('name', 'grade',)


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='아이디')
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput())

src/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Profile
from .forms import MentorForm, MenteeForm, MentorUpdateForm, MenteeUpdateForm
from mentoring.models import Mentoring

# Create your views here.
def signup_choice(request):
    return render(request, 'accounts/signup_choice.html')


#멘토 가입
def mentor_signup(request):
    if request.user.is_anonymous:
        if request.method == 'POST':
            form = MentorForm(request.POST, request.FILES)
            if form.is_valid():
                user = form.save()
                authenticated_user = authenticate(username=form.cleaned_data['username'],
                    password=form.cleaned_data['password1'])
                login(request, authenticated_user)
                messages.success(request, '환영합니다. :)')
                return redirect('/')
        else:
            form = MentorForm()
        return render(request, 'accounts/mentor_signup.html', {'form': form,})
    else:
        messages.info(request, "이미 로그인되어있습니다. 로그아웃 이후 실행해주세요.")
        return redirect('index')


#멘티 가입
def mentee_signup(request):
    if request.user.is_anonymous:
        if request.method == 'POST':
            form = MenteeForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.save()
                authenticated_user = authenticate(username=form.cleaned_data['username'],
                    password=form.cleaned_data['password1'])
                login(request, authenticated_user)
                messages.info(request, '환영합니다. :)')
                return redirect('/')
        else:
            form = MenteeForm()
        return render(request, 'accounts/mentee_signup.html', {'form': form,})
    else:
        messages.info(request, "이미 로그인되어있습니다. 로그아웃 이후 실행해주세요.")
        return redirect('index')


@login_required
def profile(request):
    user = get_object_or_404(User, pk=request.user.pk)
    profile = get_object_or_404(Profile, pk=request.user.profile.pk)
    mentoring_list = Mentoring.objects.all()
    mentoring_mine = []
    for mentoring in mentoring_list:
        if mentoring.author==request.user:
            mentoring_mine.append(mentoring)
        elif mentoring.acceptor==profile.phone:
            mentoring_mine.append(mentoring)
        else:
            pass
    if profile.is_mentor:
        return render(request, 'accounts/mentor_profile.html', {
            'user' : user,
            'profile' : profile,
            'mentoring_mine' : mentoring_mine,
            })
    else:
        return render(request, 'accounts/mentee_profile.html', {
            'user' : user,
            'profile' : profile,
            'mentoring_mine' : mentoring_mine,
            })


def profile_edit(request):
    user = get_object_or_404(User, pk=request.user.pk)
    if user.profile.is_mentor:
        if request.method == 'POST' :
            form = MentorUpdateForm(request.POST, instance = user.profile)
            if form.is_valid():
                form.save()
                return redirect('profile')
        else:
            form = MentorUpdateForm(instance=user.profile)
        return render(request, 'accounts/mentor_signup_edit.html', {'user': user, 'form': form, })
    else:
        if request.method == 'POST':
            form = MenteeUpdateForm(request.POST, instance=user.profile)
            if form.is_valid():
                form.save()
                return redirect('profile')
        else:
            form = MenteeUpdateForm(instance=user.profile)
        return render(request, 'accounts/mentee_signup_edit.html', {'user': user, 'form': form, })


def access_terms(request):
    return render(request, 'accounts/access_terms.html')


def personal_info_terms(request):
    return render(request, 'accounts/personal_info_terms.html')

src/accounts/templates/accounts/mentee_signup.html
{% extends 'accounts/mentor_signup.html' %}

src/accounts/templates/accounts/mentee_signup_edit.html
{% extends 'accounts/mentor_signup_edit.html' %}

src/accounts/templates/accounts/mentor_signup.html
{% extends 'mentoring/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}




{% block style %}
    <link href="{% static 'signup.css' %}" rel="stylesheet">
    <style>
    .text-align-center {
        text-align:center;
    }
    body {
        padding-top: 80px;
    }
    </style>
    <style type="text/css">
    .radio {
        display: inline-block;
        border-radius: 3px;
        margin: 10px 1px;
        border: 1px solid #aaa;
    }
    .radio:hover, .radio:focus, .radio:active {
        background-color: #aaa;
    }
    .radio label {
        padding:5px;
    }
    </style>

{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
    <div class="col-sm-4 col-sm-offset-4"style="margin-top: 3%;margin-bottom: 3%;">
        <p class="lead text-align-center"><strong>회원 가입</strong></p>
        <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary pull-right">{% bootstrap_icon "ok-sign" %} 확인 </button>
            {% endbuttons %}
        </form>
    </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
$(document).ready(function(){

    var address = $('#id_address').val();
    $('#map_search').children('input').val(address);

    $('#map_search').children('input').click(function(){
        var address = $('#id_address').val();
        $(this).val(address);
        alert('검색 버튼을 꼭 눌러서 확인해주세요');
    });

    $('input:checked').parent().css('background-color', '#aaa');

    function selectedRadioColor(radioInput){
        $(radioInput).on('change', function() {
        $(radioInput).parent().css('background-color', 'white');
        $(this).parent().css('background-color', '#aaa');
        });
    };

    selectedRadioColor('#id_major input');
    selectedRadioColor('#id_admission_type input');
});
</script>


{% endblock %}

src/accounts/templates/accounts/mentor_signup_edit.html
{% extends 'mentoring/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}




{% block style %}
    <link href="{% static 'signup.css' %}" rel="stylesheet">
    <style>
    .text-align-center {
        text-align:center;
    }
    body {
        padding-top: 80px;
    }
    </style>
    <style type="text/css">
    .radio {
        display: inline-block;
        border-radius: 3px;
        margin: 10px 1px;
        border: 1px solid #aaa;
    }
    .radio:hover, .radio:focus, .radio:active {
        background-color: #aaa;
    }
    .radio label {
        padding:5px;
    }
    </style>

{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
    <div class="col-sm-4 col-sm-offset-4"style="margin-top: 3%;margin-bottom: 3%;">
        <p class="lead text-align-center"><strong>회원 정보 수정</strong></p>
        <form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary pull-right">{% bootstrap_icon "ok-sign" %} 확인 </button>
            {% endbuttons %}
        </form>
    </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
$(document).ready(function(){

    var address = $('#id_address').val();
    $('#map_search').children('input').val(address);

    $('#map_search').children('input').click(function(){
        var address = $('#id_address').val();
        $(this).val(address);
        alert('검색 버튼을 꼭 눌러서 확인해주세요');
    });

    $('input:checked').parent().css('background-color', '#aaa');

    function selectedRadioColor(radioInput){
        $(radioInput).on('change', function() {
        $(radioInput).parent().css('background-color', 'white');
        $(this).parent().css('background-color', '#aaa');
        });
    };

    selectedRadioColor('#id_major input');
    selectedRadioColor('#id_admission_type input');
});
</script>


{% endblock %}