src/QNA/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.qna_main, name='qna_main'),
    url(r'^list/$', views.question_list, name='question_list'),
    url(r'^(?P<pk>\d+)/$', views.question_detail, name='question_detail'),
    url(r'^new/$', views.question_new, name='question_new'),
    url(r'^(?P<pk>\d+)/edit/$', views.question_edit, name='question_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.question_delete, name='question_delete'),
    url(r'^(?P<pk>\d+)/answer/new/$', views.answer_new, name='answer_new'),
    url(r'^(?P<pk>\d+)/answer/(?P<answer_pk>\d+)/edit/$', views.answer_edit, name='answer_edit'),
    url(r'^(?P<pk>\d+)/answer/(?P<answer_pk>\d+)/delete/$', views.answer_delete, name='answer_delete'),
    url(r'^FAQ/$', views.faq_list, name='faq_list'),
    url(r'^FAQ/(?P<pk>\d+)/$', views.faq_detail, name='faq_detail'),



]

src/mentoring/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.mentoring_list, name='mentoring_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.mentoring_detail, name='mentoring_detail'),
    url(r'^new/$', views.mentoring_new, name='mentoring_new'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.mentoring_edit, name='mentoring_edit'),
    url(r'^(?P<pk>[0-9]+)/plan/new/$', views.plan_new, name='plan_new'),
    url(r'^(?P<pk>[0-9]+)/plan/edit/$', views.plan_edit, name='plan_edit'),
    url(r'^(?P<pk>[0-9]+)/plan/$', views.plan_detail, name='plan_detail'),
    url(r'^(?P<pk>[0-9]+)/mentorfeedback/new/$', views.mentorfeedback_new, name='mentorfeedback_new'),
    url(r'^(?P<pk>[0-9]+)/mentorfeedback/edit/$', views.mentorfeedback_edit, name='mentorfeedback_edit'),
    url(r'^(?P<pk>[0-9]+)/mentorfeedback/$', views.mentorfeedback_detail, name='mentorfeedback_detail'),
    url(r'^(?P<pk>[0-9]+)/menteefeedback/new/$', views.menteefeedback_new, name='menteefeedback_new'),
    url(r'^(?P<pk>[0-9]+)/menteefeedback/edit/$', views.menteefeedback_edit, name='menteefeedback_edit'),
    url(r'^(?P<pk>[0-9]+)/menteefeedback/$', views.menteefeedback_detail, name='menteefeedback_detail'),
    url(r'^(?P<pk>\d+)/apply/new/$', views.apply_new, name='apply_new'),
    url(r'^(?P<pk>\d+)/apply/(?P<apply_pk>\d+)/edit/$', views.apply_edit, name='apply_edit'),
    url(r'^(?P<pk>\d+)/apply/(?P<apply_pk>\d+)/mentoring_authenticate/$', views.mentoring_authenticate, name='mentoring_authenticate'),
    url(r'^recommendmentor/$', views.recommendmentor_list, name='recommendmentor_list'),
    url(r'^review/$', views.review_list, name='review_list'),
    url(r'^review/(?P<pk>\d+)/$', views.review_detail, name='review_detail'),
    url(r'^Q&A/$', views.mentoring_qna_main, name='mentoring_qna_main'),
    url(r'^Q&A/list/$', views.mentoring_question_list, name='mentoring_question_list'),
    url(r'^Q&A/(?P<pk>\d+)/$', views.mentoring_question_detail, name='mentoring_question_detail'),
    url(r'^Q&A/new/$', views.mentoring_question_new, name='mentoring_question_new'),
    url(r'^Q&A/(?P<pk>\d+)/edit/$', views.mentoring_question_edit, name='mentoring_question_edit'),
    url(r'^Q&A/(?P<pk>\d+)/delete/$', views.mentoring_question_delete, name='mentoring_question_delete'),
    url(r'^Q&A/(?P<pk>\d+)/answer/new/$', views.mentoring_answer_new, name='mentoring_answer_new'),
    url(r'^Q&A/(?P<pk>\d+)/answer/(?P<mentoring_answer_pk>\d+)/edit/$', views.mentoring_answer_edit, name='mentoring_answer_edit'),
    url(r'^Q&A/(?P<pk>\d+)/answer/(?P<mentoring_answer_pk>\d+)/delete/$', views.mentoring_answer_delete, name='mentoring_answer_delete'),
    url(r'^Q&A/FAQ/$', views.mentoring_faq_list, name='mentoring_faq_list'),
    url(r'^Q&A/FAQ/(?P<pk>\d+)/$', views.mentoring_faq_detail, name='mentoring_faq_detail'),



]

src/onedayschool/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static


from django.contrib import admin

from mentoring import views as mentoring_views
from accounts import views as accounts_views

urlpatterns = [
    url(r'^$', mentoring_views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^intro/$', mentoring_views.intro, name='intro'),
    url(r'^program_info/$', mentoring_views.program_info, name='program_info'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^mentoring/', include('mentoring.urls')),
    url(r'^Q&A/', include('QNA.urls')),
    url(r'^access_terms/$', accounts_views.access_terms, name='access_terms'),
    url(r'^personal_info_terms/$', accounts_views.personal_info_terms, name='personal_info_terms'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/mentoring/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.files import File
from django.db import models
from django.utils import timezone


from onedayschool.utils import random_name_upload_to, thumbnail
from accounts.models import Profile


# Create your models here.
MAJOR_CHOICES = (
    ('간호대학', '간호대학'),
    ('경영대학', '경영대학'),
    ('농경제사회학부', '농경제사회학부'),
    ('사회과학계열', '사회과학계열'),
    ('소비자아동학부', '소비자아동학부'),
    ('의류학과', '의류학과'),
    ('인문계열', '인문계열'),
    ('국어교육과', '국어교육과'),
    ('물리교육과', '물리교육과'),
    ('사회교육과', '사회교육과'),
    ('생물교육과', '생물교육과'),
    ('역사교육과', '역사교육과'),
    ('영어교육과', '영어교육과'),
    ('지구과학교육과', '지구과학교육과'),
    ('지리교육과', '지리교육과'),
    ('체육교육과', '체육교육과'),
    ('화학교육과', '화학교육과'),
    ('건축학과', '건축학과'),
    ('물리천문학부', '물리천문학부'),
    ('바이오시스템소재학부', '바이오시스템소재학'),
    ('산림과학부', '산림과학부'),
    ('생명과학부', '생명과학부'),
    ('수리과학부', '수리과학부'),
    ('식물생산과학부', '식물생산과학부'),
    ('식품영양학과', '식품영양학과'),
    ('응용생물화학부', '응용생물화학부'),
    ('화학부', '화학부'),
    ('건설환경공학부', '건설환경공학부'),
    ('기계항공공학부', '기계항공공학부'),
    ('산업공학과', '산업공학과'),
    ('식품동물생명공학부', '식품동물생명공학부'),
    ('재료공학부', '재료공학부'),
    ('전기정보공학부', '전기정보공학부'),
    ('조경지역시스템공학부', '조경지역시스템공학부'),
    ('조선해양공학과', '조선해양공학과'),
    ('컴퓨터공학부', '컴퓨터공학부'),
    ('화학생물공학부', '화학생물공학부'),
    ('의예과', '의예과'),

)

RATING_CHOICES = (
    ('아주 높은 편', '아주 높은 편'),
    ('높은 편', '높은 편'),
    ('중간 정도', '중간 정도'),
    ('낮은 편', '낮은 편'),
    ('아주 낮은 편', '아주 낮은 편')
)


class Mentoring(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, default='1')
    acceptor = models.CharField(max_length=20, default='1', verbose_name='멘토 전화번호')
    capacity = models.PositiveSmallIntegerField(default=0)
    name = models.CharField(max_length=20, verbose_name='이름')
    area_highschool = models.CharField(max_length=40, verbose_name='지역/학교')
    grade = models.CharField(max_length=20, verbose_name='학년')
    phone_mentee = models.CharField(max_length=20, blank=True, verbose_name='학생 전화번호')
    phone_keeper = models.CharField(max_length=20, verbose_name='보호자 전화번호')
    date = models.CharField(max_length=20, verbose_name='희망 날짜')
    wannabe = models.CharField(max_length=40, verbose_name='장래희망')
    university = models.CharField(max_length=30, verbose_name='희망대학')
    rating = models.CharField(max_length=40, verbose_name='성적수준')
    will_to_study = models.CharField(max_length=30, choices=RATING_CHOICES, verbose_name='공부의욕')
    major1 = models.CharField(max_length=40, verbose_name='관심전공1')
    major2 = models.CharField(max_length=40, verbose_name='관심전공2')
    major3 = models.CharField(max_length=40, verbose_name='관심전공3')
    questions = models.TextField(max_length=2000, verbose_name='멘토링을 통해 멘토에게 답변 받고 싶은 질문')
    requirements = models.TextField(max_length=2000, verbose_name='멘토에게 바라는 점')
    is_recommended = models.PositiveSmallIntegerField(unique=True, blank=True, null=True)

    def __str__(self):
        return "멘티 : "+self.name+" ( ID : "+self.author.username+" ,  "+self.date+" )"



class Plan(models.Model):
    mentoring = models.OneToOneField(Mentoring)
    mentor = models.ForeignKey(settings.AUTH_USER_MODEL, default='1')
    mentor_intro = models.TextField(max_length=2000, verbose_name='멘토 소개 문구')
    mentor_spec = models.TextField(max_length=2000, verbose_name='약 력')
    major_intro = models.TextField(max_length=2000, verbose_name='학과 소개')
    time_manage = models.TextField(max_length=2000, verbose_name='계획표 세우는 법')
    grade_manage = models.TextField(max_length=2000, verbose_name='내신 관리 비법')
    subject_study = models.TextField(max_length=2000, verbose_name='과목별 공부법')
    know_how = models.TextField(max_length=2000, verbose_name='기타 알려주고 싶은 본인만의 특별한 공부법')
    answering_question = models.TextField(max_length=2000, verbose_name='학생의 질문에 대한 답변')
    delivering_message = models.TextField(max_length=2000, verbose_name='그 외에 학생에게 전달하고 싶은 메시지')

    def __str__(self):
        return "멘토 : " + self.mentor.profile.name + "("+self.mentor.username+") - ( 멘티 : "+self.mentoring.name+" , " + self.mentoring.date + " )"


class Apply(models.Model):
    mentoring = models.ForeignKey(Mentoring)
    content = models.TextField()
    applicant = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)


class Recommendmentor(models.Model):
    name = models.CharField(max_length=20)
    title = models.CharField(max_length=50)
    major = models.CharField(max_length=40)
    career = models.CharField(max_length=100)
    photo = models.ImageField()

    def __str__(self):
        return self.name


class Review(models.Model):
    date = models.CharField(max_length=20)
    school = models.CharField(max_length=40)
    name = models.CharField(max_length=20)
    content = models.TextField()
    photo1 = models.ImageField(blank=True)
    photo2 = models.ImageField(blank=True)
    photo3 = models.ImageField(blank=True)
    photo4 = models.ImageField(blank=True)
    photo5 = models.ImageField(blank=True)
    photo6 = models.ImageField(blank=True)

    def __str__(self):
        return self.date + " " + self.school + " " +self.name+" 후기"


class Mentorfeedback(models.Model):
    mentoring = models.OneToOneField(Mentoring)
    mentor = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)
    dream = models.TextField(max_length=2000, verbose_name="학생의 꿈은 무엇인가요?")
    happiness = models.TextField(max_length=2000, verbose_name="학생은 언제 가장 행복해하나요?")
    worry = models.TextField(max_length=2000, verbose_name="학생의 현재 가장 큰 고민은 무엇인가요?")
    subjects = models.TextField(max_length=2000, verbose_name="학생이 가장 좋아하는 과목, 잘하는 과목, 부족한 과목은 무엇이고, 그 원인은 무엇인가요?")
    future_path = models.TextField(max_length=2000, verbose_name="학생이 원하는 진로와 그 진로를 택하게 된 근거. 그에 대한 멘토의 조언(행복과 연관지어)")
    lifestyle = models.TextField(max_length=2000, verbose_name="학생의 생활패턴(시간 관리)분석 및 칭찬할 점과 보완했으면 하는 점")
    sw =models.TextField(max_length=2000, verbose_name="학생의 장점 및 부족한 점(정서적 측면에서 토닥이며 학습 동기를 유발할 수 있도록)")
    reference = models.TextField(max_length=2000, verbose_name="집에서 학생을 지도할 때 참고했으면 하는 내용")

    def __str__(self):
        return " 멘토 : "+self.mentor.profile.name +" ( 멘티 : "+ self.mentoring.name +" , "+ self.mentoring.date + " ) "


class Menteefeedback(models.Model):
    mentoring = models.OneToOneField(Mentoring)
    mentee = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)
    impression = models.TextField(max_length=2000, verbose_name="오늘 멘토링을 받고 난 기분이 어떤가요?")
    expect = models.TextField(max_length=2000, verbose_name="멘토링 받기 전에 기대하는 것이 있었나요? 그렇다면 어느 정도 해결되었나요?")
    inconvinience = models.TextField(max_length=2000, verbose_name="아직 아쉬운 점이 있다면 질문으로 적어주세요.")
    touring_rating = models.PositiveSmallIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)], verbose_name='투어 평점')
    touring_rating_reason = models.TextField(max_length=2000, verbose_name="그 이유는 무엇인가요? 개선했으면 하는 점")
    mentor_rating = models.PositiveSmallIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)], verbose_name='멘토 평점')
    mentor_rating_reason = models.TextField(max_length=2000, verbose_name="멘토는 어떤 사람인가요? 어떤 점이 매력인가요?")
    mirroring = models.TextField(max_length=2000, verbose_name="나는 멘토의 어떤 면을 닮고 싶은가요? 어떻게 하면 그 모습을 닮을 수 있을까요?")
    wannabe = models.TextField(max_length=2000, verbose_name="원하는 멘토상")
    mentoring_rating = models.PositiveSmallIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)], verbose_name='멘토링 평점')
    mentoring_rating_reason = models.TextField(max_length=2000, verbose_name="이 프로그램을 통해 얼마나 진로에 대해 이해할 수 있었나요?")
    helpness = models.TextField(max_length=2000, verbose_name="이 프로그램을 통해 학교생활을 적극적으로 하는데 도움이 될 것 같은가요?")
    onetime= models.TextField(max_length=2000, verbose_name="1회성 멘토 서비스에 만족하나요? 만일 지속적인 멘토링을 받고 싶다면 어떻게 운영되면 좋을까요?")

    def __str__(self):
        return " 멘티 : " + self.mentoring.name + " ( " + self.mentoring.date + " ) "



class Mentoring_question(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=50, verbose_name='제목')
    content = models.TextField(verbose_name='질문내용')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Mentoring_answer(models.Model):
    question = models.ForeignKey(Mentoring_question)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField(verbose_name='답변')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question.title


class Mentoring_faq(models.Model):
    question_title = models.CharField(max_length=100)
    question_content = models.TextField()
    answer_title = models.CharField(max_length=200)
    answer_content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_title

src/mentoring/templates/mentoring/intro.html
{% extends 'mentoring/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}



{% block headjs %}
<script src="{% static 'jquery-1.12.0.js' %}"></script>
<script src="{% static 'bootstrap-3.3.6/js/bootstrap.min.js' %}"></script>




<!-- 로그인 버튼 누르면 로그인 Modal이 뜨는 jquery -->
<script>
$(document).ready(function(){
    $("#loginBtn").click(function(){
        $("#loginModal").modal();
    });
});
</script>
<!-- 스크롤이 비디오 넘어가면 비디오 pause시키는 jquery -->
<script>
    $(window).scroll(function(){
        if ($(window).scrollTop() > (10+$('#video1').height()+$('#top_nav').height()+$('#logo_div').height()))
                {$('#video1')[0].pause();}

        else    {$('#video1')[0].play();}
});
</script>




{% endblock %}




{% block style %}
<style>


    #Intropage {
      padding: 0 0 0 0;
      width : 100%;

    }

    #Intropage div {
      min-height : 100px;
      width: 100%;
    }
    #video-wrap {
      position: relative;
      width: 100%;
      z-index: 999;
    }
    .main-play-shade {
    background: #fff url(/static/img/ajax-loader.gif) no-repeat center center;
    }
    #video1 {
    position: relative;
    object-fit: fill;
    z-index: 999;
    }
    .crop {
      overflow: hidden;
    }
    .crop video {
      margin: -10px 0px -10px 0px;
    }

</style>
{% endblock %}

{% block content %}



<div class="container-fluid" id="Intropage">

  <!--<img src='{% static 'img/SNU_background.png' %}' style="position:fixed; ;z-index:-5;width:100%; height: 300px; margin-top:0%;opacity: 0.9;"/>-->
    <div id="content_1" style="background-color: white;margin-bottom: 0%; ">
      <div id="video-wrap" style="width:100%; padding-bottom:5%;">
        <div class="main-play-shade" style="z-index: 999;width: 100%;position: absolute;top: 0px;left: 0px;display: none;"></div>
        <p class="crop"><video id="video1"class="video" src="{% static 'img/sharpa2.mp4' %}" style="width:102%; overflow: hidden; margin-left: -5px;  " autoplay loop="loop" controls></video></p>
      </div>
    </div>




<!-- Container (회사 소개 section)-->
    <div id="content_2" class="container text-center" style="margin-top:0px;background-color: white; padding-top: 0px;padding-bottom: 0px;">

      <br><hr>

          <h1 style="text-align: center"><img src='{% static 'img/team_info.png' %}' style="width:100%;" /></h1>
          <br><br>


    </div>

    <div id="content_3" class="container text-center" style="background-color: white;">

    <h1 style="text-align: center"><img src='{% static 'img/team_member.png' %}' style="width:100%;" /></h1>
    </div>







</div>




{% endblock %}

src/mentoring/templates/mentoring/menteefeedback_form.html
{% extends 'mentoring/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block style %}
    <link rel="stylesheet" href="{% static 'plan_form.css' %}" />
{% endblock %}


{% block content %}

{% if user == mentoring.author %}
<div class="container">
    <div class="row">
    <div class="col-sm-8 col-sm-offset-2 text-center">
        <h2><strong>멘토링 후기 쓰기</strong></h2>
    </div>

    <div class="col-sm-6 col-sm-offset-3">
        <form method="post" action="">
            {% csrf_token %}
            {% bootstrap_field menteefeedbackform.impression %}
            {% bootstrap_field menteefeedbackform.expect %}
            {% bootstrap_field menteefeedbackform.inconvinience %}
            {% bootstrap_field menteefeedbackform.touring_rating %}
            <div><p><strong>투어 별점주기 </strong></p><span style="color:#E0371A" class='touring_rating'><i class='fa fa-star-o fa-2x' value=1></i><i class='fa fa-star-o fa-2x' value=2></i><i class='fa fa-star-o fa-2x' value=3></i><i class='fa fa-star-o fa-2x' value=4></i><i class='fa fa-star-o fa-2x' value=5></i></span></div><br />
            {% bootstrap_field menteefeedbackform.touring_rating_reason %}
            {% bootstrap_field menteefeedbackform.mentor_rating %}
            <div><p><strong>멘토 별점주기 </strong></p><span style="color:#E0371A" class='mentor_rating'><i class='fa fa-star-o fa-2x' value=1></i><i class='fa fa-star-o fa-2x' value=2></i><i class='fa fa-star-o fa-2x' value=3></i><i class='fa fa-star-o fa-2x' value=4></i><i class='fa fa-star-o fa-2x' value=5></i></span></div><br />
            {% bootstrap_field menteefeedbackform.mentor_rating_reason %}
            {% bootstrap_field menteefeedbackform.mirroring %}
            {% bootstrap_field menteefeedbackform.wannabe %}
            {% bootstrap_field menteefeedbackform.mentoring_rating %}
            <div><p><strong>멘토링 별점주기 </strong></p><span style="color:#E0371A" class='mentoring_rating'><i class='fa fa-star-o fa-2x' value=1></i><i class='fa fa-star-o fa-2x' value=2></i><i class='fa fa-star-o fa-2x' value=3></i><i class='fa fa-star-o fa-2x' value=4></i><i class='fa fa-star-o fa-2x' value=5></i></span></div><br />
            {% bootstrap_field menteefeedbackform.mentoring_rating_reason %}
            {% bootstrap_field menteefeedbackform.helpness %}
            {% bootstrap_field menteefeedbackform.onetime %}
            <hr />
            {% buttons %}
                <button type="submit" class="btn btn-primary">{% bootstrap_icon "ok-sign" %} 제출</button>
            {% endbuttons %}
        </form>
    </div>
    </div>
</div>

{% else %}
자신이 받은 멘토링의 후기만 쓸 수 있습니다.
{% endif %}

{% endblock %}

{% block js %}
<script>
$(document).ready(function(){

    $('.ratings').each(function(){
      numStars = Math.round($(this).attr('value'));
      displayedStars = "";
      for (i=0; i<numStars; i++) {
        displayedStars += "<i class='fa fa-star'></i>";
      };
      for (i=0; i < 5-numStars; i++){
        displayedStars += "<i class='fa fa-star-o'></i>";
      };
      $(this).html(displayedStars);
    });

    $('.touring_rating').children('i').click(function(){
        var passedStarValue = $(this).attr("value");
        $(this).siblings().removeClass('selected');

        $(this).addClass('selected');
        $(this).addClass('fa-star');
        $(this).removeClass('fa-star-o');

        $("i.selected").nextAll().removeClass('fa-star');
        $("i.selected").nextAll().addClass('fa-star-o');

        $("i.fa-star").prevAll().removeClass('fa fa-star-o');
        $("i.fa-star").prevAll().addClass('fa fa-star');

        $('#id_touring_rating').val(passedStarValue);
    });

    $('.mentor_rating').children('i').click(function(){
        var passedStarValue = $(this).attr("value");
        $(this).siblings().removeClass('selected');

        $(this).addClass('selected');
        $(this).addClass('fa-star');
        $(this).removeClass('fa-star-o');

        $("i.selected").nextAll().removeClass('fa-star');
        $("i.selected").nextAll().addClass('fa-star-o');

        $("i.fa-star").prevAll().removeClass('fa fa-star-o');
        $("i.fa-star").prevAll().addClass('fa fa-star');

        $('#id_mentor_rating').val(passedStarValue);
    });

    $('.mentoring_rating').children('i').click(function(){
        var passedStarValue = $(this).attr("value");
        $(this).siblings().removeClass('selected');

        $(this).addClass('selected');
        $(this).addClass('fa-star');
        $(this).removeClass('fa-star-o');

        $("i.selected").nextAll().removeClass('fa-star');
        $("i.selected").nextAll().addClass('fa-star-o');

        $("i.fa-star").prevAll().removeClass('fa fa-star-o');
        $("i.fa-star").prevAll().addClass('fa fa-star');

        $('#id_mentoring_rating').val(passedStarValue);
    });
});
</script>
{% endblock %}

src/mentoring/templates/mentoring/mentoring_form.html
{% extends 'mentoring/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block style %}
    <link rel="stylesheet" href="{% static 'mentoring_form.css' %}" />
    <style type="text/css">
    .radio {
        display: inline-block;
        border-radius: 3px;
        margin: 10px 1px;
        border: 1px solid #aaa;
    }
    .radio:hover, .radio:focus, .radio:active {
        background-color: #aaa;
    }
    .radio label {
        padding:5px;
    }
    </style>
{% endblock %}


{% block content %}

{% if user.profile.is_mentor %}
<div class="container">
    <div class="row">
    <div class="col-sm-8 col-sm-offset-2 text-center">
        <div class="jumbotron" style="background-color: transparent;">
        <h3><strong>멘토링 신청은 멘티만 할 수 있습니다.</strong></h3>
        <div style="height: 50px;">
        </div>
        <a href="/" style="text-decoration: none;"><h4><strong>홈페이지로 돌아가기</strong></h4></a>
        </div>
    </div>

    <div class="col-sm-6 col-sm-offset-3">

    </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row">
    <div class="col-sm-8 col-sm-offset-2 text-center">
        <h2><strong>멘토링 신청하기</strong></h2>
    </div>

    <div class="col-sm-6 col-sm-offset-3">
        <form method="post" action="">
            {% csrf_token %}
            {% bootstrap_form mentoringform %}
            <hr />
            {% buttons %}
                <h1 style="text-align:center;"><button type="submit" class="btn btn-primary">{% bootstrap_icon "ok-sign" %} 신청하기</button></h1>
            {% endbuttons %}
        </form>
    </div>
    </div>
</div>
{% endif %}

{% endblock %}

{% block script %}
<script>
$(document).ready(function(){
    $('input:checked').parent().css('background-color', '#aaa');

    function selectedRadioColor(radioInput){
        $(radioInput).on('change', function() {
        $(radioInput).parent().css('background-color', 'white');
        $(this).parent().css('background-color', '#aaa');
        });
    };

    selectedRadioColor('#id_will_to_study input');



});
</script>
{% endblock %}

src/mentoring/templates/mentoring/recommendmentor_list.html
{% extends 'mentoring/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    {% for recommendmentor in recommendmentor_list %}
    <div class="col-md-12">
        <div class="col-sm-3">
        <img src="{{recommendmentor.photo.url}}" style="width:80px; height=:80px;"/>
        <hr/>
        {{recommendmentor.name}}
        </div>
        <div class="col-sm-9">
        <h3>{{recommendmentor.title}}</h3>
        <h5>{{recommendmentor.major}}</h5>
        <p>{{recommendmentor.career}}</p>
        </div>
    </div>
    {% endfor %}
</div>